[font]
size = 14

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[window]
padding.x = 10
padding.y = 10
opacity = 0.8
decorations = "Buttonless"
blur=true

