[font]
size = 14

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[window]
opacity = 0.95
decorations = "buttonless"

[window.padding]
x = 8
y = 8

